# More colors were needed
[colors]
alt_foreground = "#777777"
background = "#0e0e0e"
foreground = "#ffffff"
cursor = "#00ffff"

[cursor]
cursor_type = "Beam" # Hollow beam line box
cursor_thickness = 1 # Currently useless

[line_num]
relative = true
zero_indexing = false