[colors]
background = "#0e0e0e"
foreground = "#ffffff"
cursor = "#00ffff"
alt_foreground = "#777777"

[cursor]
cursor_type = "Beam" # Hollow beam line box
cursor_thickness = 1

[line_num]
relative = true
zero_indexing = false