# More colors were needed
[colors]
alt_foreground = "#777777"
background = "#0e0e0e"
foreground = "#ffffff"
cursor = "#00ffff"
transparency = 0.5
border = "#00ffff"

[cursor]
cursor_thickness = 2

[line_num]
relative = true
zero_indexing = false